%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\kebl3433\Documents\MATLAB\Data\16.03.14 Field data
%    notes.xlsx Worksheet: Short term (Wii)
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/04/25 13:51:45

%% Import the data, extracting spreadsheet dates in MATLAB serial date number format (datenum)
% AM Modified
% [~, ~, raw, dateNums] = xlsread('C:\Users\kebl3433\Documents\MATLAB\Data\16.03.14 Field data notes.xlsx','Short term (Wii)','A2:AJ314','',@convertSpreadsheetDates);
[~, ~, raw, dateNums] = xlsread('C:\Users\engs1602\research\data\Data Feb-Mar 2016\16.03.14 Field data notes.xlsx','Short term (Wii)','A2:AJ314','',@convertSpreadsheetDates);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,[3,4,5,8,9,10,12,15,16,17,18,19,20]);
raw = raw(:,[1,2,6,7,11,13,14,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36]);
dateNums = dateNums(:,[1,2,6,7,11,13,14,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36]);

%% Replace date strings by MATLAB serial date numbers (datenum)
R = ~cellfun(@isequalwithequalnans,dateNums,raw) & cellfun('isclass',raw,'char'); % Find spreadsheet dates
raw(R) = dateNums(R);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
File_no = data(:,1);
Date_recorded = data(:,2);
CommunityName = cellVectors(:,1);
Institution = cellVectors(:,2);
CommunityID = cellVectors(:,3);
WDTID = data(:,3);
loc_num16 = data(:,4);
Person = cellVectors(:,4);
Gender = cellVectors(:,5);
Age = cellVectors(:,6);
hands = data(:,5);
side = cellVectors(:,7);
H2L_start = data(:,6);
H2L_end = data(:,7);
H2R_start1 = cellVectors(:,8);
H2R_end1 = cellVectors(:,9);
H2R_start2 = cellVectors(:,10);
H2R_end2 = cellVectors(:,11);
H2B_START = cellVectors(:,12);
H2B_END = cellVectors(:,13);
Volume = data(:,8);
start_fill = data(:,9);
end_fill = data(:,10);
Pumpsforwater = data(:,11);
Water_starts = data(:,12);
flow1 = data(:,13);
flow_change = data(:,14);
Notes = data(:,15);
VarName29 = data(:,16);
UTM = data(:,17);
Latitute = data(:,18);
Longitude = data(:,19);
Elevation = data(:,20);
Depthbyrod = data(:,21);
Borehole = data(:,22);
Waterlevel = data(:,23);

%% Clear temporary variables
clearvars data raw dateNums cellVectors R;

